-- Portal Cumplidos (prefijo pc_) · Solo CREA tablas si no existen.
-- Columnas ampliadas: snapshot API al consultar + cumplido del conductor al completar.
-- Migraciones en sql/migrations/ para bases ya creadas.

CREATE TABLE IF NOT EXISTS pc_entrega_sap (
  id CHAR(36) PRIMARY KEY,
  numero_entrega VARCHAR(50) NOT NULL,
  pedido VARCHAR(50) NULL,
  cliente VARCHAR(255) NULL,
  direccion VARCHAR(500) NULL,
  ciudad VARCHAR(100) NULL,
  region VARCHAR(120) NULL,
  estado_logistico VARCHAR(50) NULL,
  transportista_asignado VARCHAR(150) NULL,
  placa_asignada VARCHAR(20) NULL,
  fecha_planificada DATE NULL,
  volumen VARCHAR(50) NULL,
  peso VARCHAR(50) NULL,
  fuente_sap VARCHAR(30) NULL,
  tknum VARCHAR(20) NULL,
  tipo_entrega VARCHAR(20) NULL,
  codigo_cliente VARCHAR(30) NULL,
  ruta VARCHAR(120) NULL,
  tipo_transporte VARCHAR(80) NULL,
  clase_medio_transporte VARCHAR(80) NULL,
  procesamiento_especial VARCHAR(80) NULL,
  nombre_transporte VARCHAR(255) NULL,
  conductor_nombre VARCHAR(150) NULL,
  conductor_documento VARCHAR(30) NULL,
  conductor_telefono VARCHAR(30) NULL,
  empresa_transportista VARCHAR(150) NULL,
  empresa_transportista_codigo VARCHAR(30) NULL,
  placa_sap VARCHAR(20) NULL,
  fecha_documento DATE NULL,
  items_count INT NOT NULL DEFAULT 0,
  api_consultada_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  datos_sap JSON NULL,
  sincronizado_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_pc_entrega_sap_numero (numero_entrega),
  INDEX idx_pc_entrega_sap_sync (sincronizado_at),
  INDEX idx_pc_entrega_tknum (tknum),
  INDEX idx_pc_entrega_cliente (codigo_cliente)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pc_registro_cumplido (
  id CHAR(36) PRIMARY KEY,
  entrega_sap_id CHAR(36) NULL,
  numero_entrega VARCHAR(50) NOT NULL,
  tknum VARCHAR(20) NULL,
  estado ENUM('borrador', 'completado') NOT NULL DEFAULT 'borrador',
  modo ENUM('ok', 'nov') NULL,
  estado_resultado ENUM('entrega_exitosa', 'no_contesto') NULL,
  transportista VARCHAR(150) NOT NULL DEFAULT '',
  placa VARCHAR(20) NOT NULL DEFAULT '',
  fecha_entrega DATE NULL,
  hora_entrega TIME NULL,
  observaciones TEXT NULL,
  n_intentos INT NULL,
  visita_1_fecha DATE NULL,
  visita_1_hora TIME NULL,
  visita_2_fecha DATE NULL,
  visita_2_hora TIME NULL,
  visita_3_fecha DATE NULL,
  visita_3_hora TIME NULL,
  chk_llamadas TINYINT(1) DEFAULT 0,
  chk_whatsapp TINYINT(1) DEFAULT 0,
  chk_cliente_ausente TINYINT(1) NOT NULL DEFAULT 0,
  chk_cliente_rechaza TINYINT(1) NOT NULL DEFAULT 0,
  chk_material_no_solicitado TINYINT(1) NOT NULL DEFAULT 0,
  chk_entrega_parcial TINYINT(1) NOT NULL DEFAULT 0,
  descripcion_novedad TEXT NULL,
  terminos_aceptados TINYINT(1) NOT NULL DEFAULT 0,
  completado_at TIMESTAMP NULL DEFAULT NULL,
  sap_estado VARCHAR(30) NULL,
  sap_mensaje VARCHAR(500) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_pc_registro_numero (numero_entrega),
  INDEX idx_pc_registro_estado (estado),
  INDEX idx_pc_registro_resultado (estado_resultado),
  INDEX idx_pc_registro_entrega (entrega_sap_id),
  INDEX idx_pc_registro_tknum (tknum),
  INDEX idx_pc_registro_completado (completado_at),
  CONSTRAINT fk_pc_registro_entrega_sap
    FOREIGN KEY (entrega_sap_id) REFERENCES pc_entrega_sap(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pc_adjunto (
  id CHAR(36) PRIMARY KEY,
  registro_cumplido_id CHAR(36) NOT NULL,
  tipo ENUM('cumplido', 'ev_lugar', 'ev_captura', 'ev_aviso') NOT NULL DEFAULT 'cumplido',
  nombre_original VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  tamano_bytes INT NOT NULL,
  ruta_almacenamiento VARCHAR(500) NOT NULL,
  hash_sha256 CHAR(64) NULL,
  estado_sync_sap ENUM('pendiente', 'ok', 'error') DEFAULT 'pendiente',
  sap_doc_id VARCHAR(100) NULL,
  intentos_sync INT DEFAULT 0,
  ultimo_error VARCHAR(500) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_pc_adjunto_registro (registro_cumplido_id),
  INDEX idx_pc_adjunto_sync (estado_sync_sap),
  CONSTRAINT fk_pc_adjunto_registro
    FOREIGN KEY (registro_cumplido_id) REFERENCES pc_registro_cumplido(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pc_auditoria (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  entidad VARCHAR(50) NOT NULL,
  entidad_id VARCHAR(36) NOT NULL,
  accion VARCHAR(50) NOT NULL,
  detalle JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_pc_auditoria_entidad (entidad, entidad_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
